name: 'Enhansome (Awesome with stars)'
description: 'Enhance "Awesome <Links>". Adds stars, issues, last activity along with find and replace.'
author: 'v1nvn'

branding:
  icon: 'star'
  color: 'yellow'

inputs:
  github_token:
    description: 'GitHub token for fetching star counts and committing.'
    required: true
  submodule_path:
    description: 'Path to the submodule directory within the main repository.'
    required: false
    default: 'origin'
  content_destination_path:
    description: 'Path in the main repository where submodule content should be synced to (e.g., "." for root).'
    required: false
    default: '.'
  file_to_enhance:
    description: 'Path to the markdown file (relative to content_destination_path) to enhance with stars.'
    required: false
    default: 'README.md'
  items_to_sync:
    description: |
      Space-separated list of files and/or directories to sync from the source_path.
      Paths should be relative to the source_path.
      Example: "README.md images/logo.png docs/"
    required: false
    default: 'README.md'
  extra_rsync_args:
    description: 'Any extra arguments to pass to rsync for the sync-submodule-content step.'
    required: false
    default: ''
  find_and_replace:
    description: |
      Multiline list of literal string replacements for the enhancement step.
      Each line should be in the format: `find_string:::replace_string`.
    required: false
  regex_find_and_replace:
    description: |
      Multiline list of regex-based replacements for the enhancement step.
      Each line should be in the format: `pattern:::replacement_string`.
    required: false
  disable_branding:
    description: "Set to 'true' to disable the default behavior of appending ' with stars' to Awesome list titles."
    required: false
    default: 'false'
  sort_by:
    description: "Sorts lists that meet the threshold. Options: 'stars' or 'last_commit'. Leave empty to disable sorting."
    required: false
    default: 'stars'


  # Commit and Push Inputs
  do_commit:
    description: 'Whether to commit and push changes after enhancement.'
    required: false
    default: 'true'
  commit_message:
    description: 'Commit message for the changes.'
    required: false
    default: 'docs(enhance): ✨ Auto-update list with latest content & stars'
  commit_user_name:
    description: 'Name for the commit author.'
    required: false
    default: 'Enhansome'
  commit_user_email:
    description: 'Email for the commit author.'
    required: false
    default: 'actions-bot@users.noreply.github.com'
  commit_author:
    description: 'Commit author string. Defaults to "commit_user_name <commit_user_email>".'
    required: false
  commit_branch:
    description: 'Branch to commit to. Defaults to the current branch.'
    required: false
  commit_file_pattern:
    description: 'File pattern to add to commit. Defaults to all changes "."'
    required: false
    default: '.'
  commit_options:
    description: 'Additional options for git commit (e.g., --no-verify).'
    required: false
    default: ''
  push_options:
    description: 'Additional options for git push (e.g., --force).'
    required: false
    default: ''


outputs:
  changes_committed:
    description: "True if changes were committed, false otherwise."
    value: ${{ steps.commit_changes.outputs.changes_committed }}

runs:
  using: "composite"
  steps:
    - name: Link action repository for local calls
      shell: bash
      run: |
        # Create a temporary, known directory for our links
        mkdir -p ./.github/actions

        # Ensure that any remnants from a previous run are cleaned up
        rm -rf ./.github/actions/enhansome

        # Link the root of this action's source code into the user's workspace
        ln -s "${{ github.action_path }}" ./.github/actions/enhansome
        echo "Created symlink to action source at ./.github/actions/enhansome"

    - name: Update Submodule
      id: update_submodule
      uses: ./.github/actions/enhansome/update-submodule
      with:
        submodule_path: ${{ inputs.submodule_path }}

    - name: Sync Submodule Content
      id: sync_content
      uses: ./.github/actions/enhansome/sync-submodule
      with:
        source_path: ${{ inputs.submodule_path }}
        destination_path: ${{ inputs.content_destination_path }}
        items_to_sync: ${{ inputs.items_to_sync }}
        extra_rsync_args: ${{ inputs.extra_rsync_args }}

    - name: Enhance Markdown File
      id: enhance_file
      uses: ./.github/actions/enhansome/enhance-readme
      with:
        github_token: ${{ inputs.github_token }}
        markdown_file: ${{ inputs.file_to_enhance }}
        working_directory: ${{ inputs.content_destination_path }}
        find_and_replace: ${{ inputs.find_and_replace }}
        regex_find_and_replace: ${{ inputs.regex_find_and_replace }}
        disable_branding: ${{ inputs.disable_branding }}
        sort_by: ${{ inputs.sort_by }}
        relative_link_prefix: ${{ inputs.submodule_path }}



    - name: Commit and Push Changes
      id: commit_changes
      if: inputs.do_commit == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit_message }}
        commit_user_name: ${{ inputs.commit_user_name }}
        commit_user_email: ${{ inputs.commit_user_email }}
        commit_author: ${{ inputs.commit_author || format('{0} <{1}>', inputs.commit_user_name, inputs.commit_user_email) }}
        branch: ${{ inputs.commit_branch }}
        file_pattern: ${{ inputs.commit_file_pattern }}
        commit_options: ${{ inputs.commit_options }}
        push_options: ${{ inputs.push_options }}

    - name: Cleanup action repository link
      if: always()
      shell: bash
      run: rm -rf ./.github/actions