name: 'Enhance Markdown with GitHub Stars'
description: 'Parses markdown files, finds GitHub repo links, and appends star counts.'
author: 'v1nvn'

inputs:
  github_token:
    description: 'GitHub token for API calls.'
    required: true
  markdown_files:
    description: 'Space-separated list of markdown file paths to process (relative to working_directory).'
    required: true
    default: 'README.md'
  working_directory:
    description: 'The directory where the markdown files are located and where the action should operate.'
    required: false
    default: '.' # GitHub workspace root
  find_and_replace:
    description: |
      Multiline list of literal string replacements.
      Each line should be in the format: `find_string:::replace_string`.
    required: false
  regex_find_and_replace:
    description: |
      Multiline list of regex-based replacements.
      Each line should be in the format: `pattern:::replacement_string`.
      The pattern is a case-sensitive regex with `gm` flags applied.
    required: false
  disable_branding:
    description: "Set to 'true' to disable the default behavior of appending ' with stars' to Awesome list titles."
    required: false
    default: 'false'


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_MARKDOWN_FILES: ${{ inputs.markdown_files }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
    INPUT_FIND_AND_REPLACE: ${{ inputs.find_and_replace }}
    INPUT_REGEX_FIND_AND_REPLACE: ${{ inputs.regex_find_and_replace }}
    INPUT_DISABLE_BRANDING: ${{ inputs.disable_branding }}
