name: 'Enhance Markdown with GitHub Stars'
description: 'Parses markdown files, finds GitHub repo links, and appends star counts.'
author: 'v1nvn'

inputs:
  github_token:
    description: 'GitHub token for API calls.'
    required: true
  markdown_files:
    description: 'Space-separated list of markdown file paths to process (relative to working_directory).'
    required: true
    default: 'README.md'
  working_directory:
    description: 'The directory where the markdown files are located and where the action should operate.'
    required: false
    default: '.' # GitHub workspace root

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_MARKDOWN_FILES: ${{ inputs.markdown_files }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
