name: 'Update Git Submodule'
description: 'Initializes and updates a Git submodule to the latest commit on its default branch.'
author: 'v1nvn'

inputs:
  submodule_path:
    description: 'Path to the submodule directory to update.'
    required: true
    default: 'origin' # A common default name

outputs:
  submodule_owner_repo:
    description: 'The submodule repository in owner/repo format (e.g., owner/repo)'
    value: ${{ steps.update_submodule.outputs.submodule_owner_repo }}

runs:
  using: 'composite'
  steps:
    - name: Update Submodule
      id: update_submodule
      shell: bash
      run: |
        set -e
        echo "Updating submodule at path: ${{ inputs.submodule_path }}"
        if [ ! -d "${{ inputs.submodule_path }}/.git" ]; then
          echo "Submodule not initialized or path incorrect. Initializing..."
          # Initialize if .git folder is missing (might happen on first checkout without recursive)
          # Note: We do NOT use --recursive here because:
          # 1. This action only needs the immediate submodule content, not nested submodules
          # 2. Nested submodules may have misconfigured .gitmodules that cause failures
          # 3. The sync step only copies files from the immediate submodule path
          git submodule update --init "${{ inputs.submodule_path }}"
        else
          echo "Submodule already initialized."
        fi
        # Go into the submodule directory to ensure commands like pull work as expected
        # and to fetch the latest from its own remote.
        cd "${{ inputs.submodule_path }}"
        git fetch --all
        # Get the default branch of the submodule
        DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
        if [ -z "$DEFAULT_BRANCH" ]; then
          echo "Could not determine default branch for submodule. Exiting."
          exit 1
        fi
        echo "Default branch for submodule is: $DEFAULT_BRANCH"
        git checkout "$DEFAULT_BRANCH"
        git pull origin "$DEFAULT_BRANCH" --ff-only # Fast-forward only pull
        cd ..

        # After updating the submodule, its new commit hash needs to be
        # registered in the parent repository.
        # This is usually done by `git add submodule_path` in the parent repo,
        # which the calling workflow will handle before committing.
        echo "Submodule ${{ inputs.submodule_path }} updated. Parent repo should 'git add ${{ inputs.submodule_path }}' to stage changes."

        # Get the submodule's remote URL in owner/repo format
        cd "${{ inputs.submodule_path }}"
        SUBMODULE_REMOTE_URL=$(git config --get remote.origin.url)
        # Extract owner/repo from various URL formats
        # https://github.com/owner/repo.git -> owner/repo
        # git@github.com:owner/repo.git -> owner/repo
        SUBMODULE_OWNER_REPO=$(echo "$SUBMODULE_REMOTE_URL" | sed -E 's|.*github.com[/:]([^/]+/.*)|\1|' | sed 's/\.git$//')
        cd ..
        echo "submodule_owner_repo=$SUBMODULE_OWNER_REPO" >> $GITHUB_OUTPUT
        echo "Submodule repository: $SUBMODULE_OWNER_REPO"
