name: Release Please & Update Major Tag

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

  # (Optional but Recommended) Runs automatically on a schedule.
  # This example runs at 4:30 AM UTC every Monday.
  # In your local time (IST), that is 10:00 AM every Monday morning.
  # schedule:
  #   - cron: '30 4 * * 1'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT_FOR_RELEASES }}

  update-major-tag:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_FOR_RELEASES }}

      - name: Update and Push Major Version Tag
        run: |
          # Configure git user for this commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          MAJOR="${{ needs.release-please.outputs.major }}"
          MINOR="${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}"
          echo "Updating tags: Major '$MAJOR', Minor '$MINOR'"
          
          # Delete the old tags locally and on the remote.
          # The '|| true' part ensures the script doesn't fail if the tags don't exist yet.
          git tag -d "$MAJOR" || true
          git tag -d "$MINOR" || true
          git push origin "$MAJOR" "$MINOR" || true
          
          # Create new local annotated tags pointing to the release commit
          git tag -a "$MAJOR" -m "Release $MAJOR"
          git tag -a "$MINOR" -m "Release $MINOR"
          
          # Push the new tags to the remote
          git push origin "$MAJOR" "$MINOR"
